config/routes.rb
Rails.application.routes.draw do
  resources :drafts
  resources :teams
  devise_for :users
  root 'pages#about'
  get 'team', to: 'create_teams#index'
  get 'teams', to: 'teams#index'
  get 'about', to: 'pages#about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/draft.rb
class Draft < ApplicationRecord
  belongs_to :user
end

app/models/team.rb
class Team < ApplicationRecord
  belongs_to :user
  has_one_attached :logo
  has_many :users

  validates :name, presence: true, uniqueness: true


  def optimized_image(image, x, y)
    return image.variant(resize_to_fill: [x, y]).processed
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  
  def username
    return email.split("@")[0].capitalize
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception

    before_action :configure_permitted_parameters, if: :devise_controller?

    protected
    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:team, :playername, :tid])
        devise_parameter_sanitizer.permit(:account_update, keys: [:team, :playername, :tid])
    end

    helper_method :is_admin!

    private 
    def is_admin!
        if current_user && current_user.admin
        else
            redirect_to root_path
        end
    end

end

app/controllers/drafts_controller.rb
class DraftsController < ApplicationController
  before_action :set_draft, only: [:show, :edit, :update, :destroy]

  # GET /drafts
  # GET /drafts.json
  def index
    @drafts = Draft.all
  end

  # GET /drafts/1
  # GET /drafts/1.json
  def show
  end

  # GET /drafts/new
  def new
    @draft = Draft.new
  end

  # GET /drafts/1/edit
  def edit
  end

  # POST /drafts
  # POST /drafts.json
  def create
    @draft = Draft.new(draft_params)
    @draft.user = current_user

    respond_to do |format|
      if @draft.save
        format.html { redirect_to @draft, notice: 'Draft was successfully created.' }
        format.json { render :show, status: :created, location: @draft }
      else
        format.html { render :new }
        format.json { render json: @draft.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /drafts/1
  # PATCH/PUT /drafts/1.json
  def update
    respond_to do |format|
      if @draft.update(draft_params)
        format.html { redirect_to @draft, notice: 'Draft was successfully updated.' }
        format.json { render :show, status: :ok, location: @draft }
      else
        format.html { render :edit }
        format.json { render json: @draft.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /drafts/1
  # DELETE /drafts/1.json
  def destroy
    @draft.destroy
    respond_to do |format|
      format.html { redirect_to drafts_url, notice: 'Draft was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_draft
      @draft = Draft.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def draft_params
      params.require(:draft).permit(:radiant, :dire, :user_id)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  before_action :set_team, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /teams
  # GET /teams.json
  def index
    @teams = Team.all
  end

  # GET /teams/1
  # GET /teams/1.json
  def show
  end

  # GET /teams/new
  def new
    @team = Team.new
  end

  # GET /teams/1/edit
  def edit
  end

  # POST /teams
  # POST /teams.json
  def create
    @team = Team.new(team_params)
    @team.user = current_user
    @team.players = current_user.playername

    respond_to do |format|
      if @team.save
        current_user.update(team: @team.name)
        current_user.update(tid: @team.id)
        format.html { redirect_to @team, notice: 'Team was successfully created.' }
        format.json { render :show, status: :created, location: @team }
      else
        format.html { render :new }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teams/1
  # PATCH/PUT /teams/1.json
  def update
    respond_to do |format|
      if @team.update(team_params)
        format.html { redirect_to @team, notice: 'Team was successfully updated.' }
        format.json { render :show, status: :ok, location: @team }
      else
        format.html { render :edit }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teams/1
  # DELETE /teams/1.json
  def destroy
    @team.destroy
    respond_to do |format|
      format.html { redirect_to teams_url, notice: 'Team was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_team
      @team = Team.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def team_params
      params.require(:team).permit(:name, :logo, :user)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/drafts_helper.rb
module DraftsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/drafts/_form.html.erb
<%= simple_form_for(@draft) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :radiant %>
    <%= f.input :dire %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/drafts/edit.html.erb
<h1>Editing Draft</h1>

<%= render 'form', draft: @draft %>

<%= link_to 'Show', @draft %> |
<%= link_to 'Back', drafts_path %>

app/views/drafts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Drafts</h1>

<table>
  <thead>
    <tr>
      <th>Radiant</th>
      <th>Dire</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @drafts.each do |draft| %>
      <tr>
        <td><%= draft.radiant %></td>
        <td><%= draft.dire %></td>
        <td><%= draft.user_id %></td>
        <td><%= link_to 'Show', draft %></td>
        <td><%= link_to 'Edit', edit_draft_path(draft) %></td>
        <td><%= link_to 'Destroy', draft, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<div id="new-draft">
  <%= link_to 'New Draft', new_draft_path, remote: true %>
</div>

app/views/drafts/new.html.erb
<h1>New Draft</h1>

<%= render 'form', draft: @draft %>

<%= link_to 'Back', drafts_path %>

app/views/drafts/new.js.erb
$('#new-draft a').parent().html("<%= j render 'form', draft: @draft %>")

app/views/drafts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Radiant:</strong>
  <%= @draft.radiant %>
</p>

<p>
  <strong>Dire:</strong>
  <%= @draft.dire %>
</p>

<p>
  <strong>User:</strong>
  <%= @draft.user_id %>
</p>

<%= link_to 'Edit', edit_draft_path(@draft) %> |
<%= link_to 'Back', drafts_path %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href=<%= root_path %>>Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href=<%= teams_path %>>Teams</a>
      </li>
      <% if current_user %>
      <%# If default then show create option if not then show team name %>
        <% if current_user.team.nil?  %>
            <li class="nav-item">
                <%= link_to "Create team", new_team_path, class: "nav-link" %>
            </li>
        <% else %>
            <li class="nav-item">
                <%= link_to current_user.team.to_s, edit_team_path(current_user.tid.to_i), class: "nav-link" %>
            </li>
        <% end %>
      <% end %>
    </ul>

    <%# Dropdown menu %>
    <ul class="navbar-nav ml-auto">
        <% if current_user %>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <% if current_user.team.nil? %>
                    <%= current_user.playername %>
                <% else %>
                    <%= current_user.team %> | <%= current_user.playername %>
                <% end %>
                </a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                <% if current_user.admin %>
                    <a class="dropdown-item" href="#">Some admin action</a>
                <% end %>
                <a class="dropdown-item" href="<%= edit_user_registration_path %>">Account Settings</a>
                <div class="dropdown-divider"></div>
                <%= link_to "Logout", destroy_user_session_path, class:'dropdown-item', method: :delete %>
                </div>
            </li>
        <% else %>
            <li class="nav-item">
                <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
                <%= link_to "Login", new_user_session_path, class: "nav-link" %>
            </li>
        <% end %>
    </ul>
    <%# <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form> %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PhilosopherMode</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/pages/_test.html.erb
<div class="container">
    <div class="jumbotron">
        <h1 class="display-4">testing</h1>
    </div>


</div>

app/views/pages/about.html.erb
<div class="container">
    <div class="jumbotron">
        <h1 class="display-4">What is Philosopher Mode?</h1>
    </div>

    <div style=overflow-y:hidden">
        <% if current_user %>
        <%= current_user.attributes %>
        <% end %>

    </div>
</div>